

#ifndef MATH_H_    // These are called as include guards. Include guards are written using pre-processor directives.
#define MATH_H_    // MATH_H_ can be any value. This is generated by default. it avoids multiple inclusion of the contents of the same header file in a project.

// Function protypes of math.c are given in this header file to allow main to reach them durin pre-processor process.
// These are also called as exposed function prototypes.

int math_add(int n1, int n2);
int math_sub(int n1, int n2);
long long int math_mul(int n1, int n2);
float math_div(int n1, int n2);

#endif
